<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Cronos" Version="0.9.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="BackupDatabaseTransformBlock.cs">
        <DependentUpon>BackupPipeline.cs</DependentUpon>
      </Compile>
      <Compile Update="UploadBackupTransformBlock.cs">
        <DependentUpon>BackupPipeline.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AegisKeeper.Database.SQLServer\AegisKeeper.Database.SQLServer.csproj" />
      <ProjectReference Include="..\AegisKeeper.Shared\AegisKeeper.Shared.csproj" />
    </ItemGroup>

</Project>
